import React, { useState, useEffect, useRef } from 'react';
import '../styles/kanban.css';
import { apiClient } from '../api/client';

interface CreateCardModalProps {
    onClose: () => void;
    onSubmit: (data: any) => void;
    initialBoardId?: string;
    editingCard?: any;
}

export function CreateCardModal({ onClose, onSubmit, initialBoardId, editingCard }: CreateCardModalProps) {
    const modalRef = useRef<HTMLDivElement>(null);
    const [title, setTitle] = useState(editingCard?.title || '');
    const [priority, setPriority] = useState(editingCard?.priority || 'medium');
    const [assigneeId, setAssigneeId] = useState(editingCard?.assigneeId || '');
    const [opdsl, setOpdsl] = useState(editingCard?.opdsl ? new Date(editingCard.opdsl).toISOString().split('T')[0] : '');
    const [users, setUsers] = useState<any[]>([]);
    const [boards, setBoards] = useState<any[]>([]);
    const [selectedBoardId, setSelectedBoardId] = useState(editingCard?.boardId || initialBoardId || '');

    const [cardType, setCardType] = useState<'ORDER' | 'QUOTE'>(editingCard?.type || 'ORDER');
    const [productType, setProductType] = useState(editingCard?.productType || '');
    const [specs, setSpecs] = useState(editingCard?.specs || '');
    const [customerName, setCustomerName] = useState(editingCard?.customerName || '');

    // Close on click outside
    useEffect(() => {
        function handleClickOutside(event: MouseEvent) {
            if (modalRef.current && !modalRef.current.contains(event.target as Node)) {
                onClose();
            }
        }
        document.addEventListener('mousedown', handleClickOutside);
        return () => document.removeEventListener('mousedown', handleClickOutside);
    }, [onClose]);

    useEffect(() => {
        const fetchData = async () => {
            try {
                // Fetch Users
                const usersRes: any = await apiClient.get('/users');
                setUsers(usersRes);

                // Fetch Boards if no initialBoardId (or even if there is, we might want to change board if editing?)
                // For now, if editing, we might want to see all boards to move it? Or just lock board.
                // Replicating existing logic:
                if (!initialBoardId) {
                    const boardsRes: any = await apiClient.get('/boards/mine');
                    setBoards(boardsRes);
                    if (boardsRes.length > 0 && !selectedBoardId) {
                        setSelectedBoardId(boardsRes[0].id);
                    }
                }
            } catch (error) {
                console.error('Failed to fetch data', error);
            }
        };
        fetchData();
    }, [initialBoardId, selectedBoardId]);

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (!selectedBoardId) {
            alert('Please select a board');
            return;
        }

        const payload: any = {
            title,
            priority,
            assigneeId,
            opdsl,
            boardId: selectedBoardId,
            type: cardType
        };

        if (cardType === 'QUOTE') {
            payload.productType = productType;
            payload.specs = specs;
            payload.customerName = customerName;
            // Quote ID is generated by backend
        }

        onSubmit(payload);
        onClose();
    };

    return (
        <div className="modal-overlay">
            <div className="modal-content" ref={modalRef} style={{ width: '500px' }}>
                <button className="modal-close-btn" onClick={onClose}>×</button>

                <div className="modal-header">
                    <h2 className="modal-title">
                        {editingCard ? 'Edit' : 'Create New'} {cardType === 'QUOTE' ? 'Quote' : 'Card'}
                    </h2>
                </div>

                <form onSubmit={handleSubmit} className="modal-body">
                    <div style={{ marginBottom: '1.5rem', display: 'flex', gap: '1rem' }}>
                        <button
                            type="button"
                            onClick={() => setCardType('ORDER')}
                            style={{
                                flex: 1,
                                padding: '0.5rem',
                                borderRadius: 'var(--radius-md)',
                                border: cardType === 'ORDER' ? '2px solid var(--color-primary)' : '1px solid var(--color-border)',
                                backgroundColor: cardType === 'ORDER' ? 'var(--color-primary-light)' : 'transparent',
                                color: cardType === 'ORDER' ? 'var(--color-primary)' : 'var(--color-text-secondary)',
                                fontWeight: 700,
                                cursor: 'pointer'
                            }}
                        >
                            <span role="img" aria-label="order">📋</span> ORDER CARD
                        </button>
                        <button
                            type="button"
                            onClick={() => setCardType('QUOTE')}
                            style={{
                                flex: 1,
                                padding: '0.5rem',
                                borderRadius: 'var(--radius-md)',
                                border: cardType === 'QUOTE' ? '2px solid var(--color-primary)' : '1px solid var(--color-border)',
                                backgroundColor: cardType === 'QUOTE' ? 'var(--color-primary-light)' : 'transparent',
                                color: cardType === 'QUOTE' ? 'var(--color-primary)' : 'var(--color-text-secondary)',
                                fontWeight: 700,
                                cursor: 'pointer'
                            }}
                        >
                            <span role="img" aria-label="quote">💬</span> QUOTE CARD
                        </button>
                    </div>

                    {!initialBoardId && (
                        <div style={{ marginBottom: '1.5rem' }}>
                            <label style={{ display: 'block', textTransform: 'uppercase', fontSize: '0.7rem', fontWeight: 700, color: 'var(--color-text-secondary)', marginBottom: '0.5rem' }}>
                                Board
                            </label>
                            <select
                                value={selectedBoardId}
                                onChange={(e) => setSelectedBoardId(e.target.value)}
                                style={{
                                    width: '100%',
                                    padding: '0.75rem',
                                    borderRadius: 'var(--radius-md)',
                                    border: '1px solid var(--color-border)',
                                    fontSize: '0.875rem',
                                    outline: 'none',
                                    backgroundColor: '#fff'
                                }}
                            >
                                <option value="">Select Board...</option>
                                {boards.map(b => (
                                    <option key={b.id} value={b.id}>{b.name}</option>
                                ))}
                            </select>
                        </div>
                    )}

                    {cardType === 'ORDER' ? (
                        <>
                            <div style={{ marginBottom: '1.5rem' }}>
                                <label style={{ display: 'block', textTransform: 'uppercase', fontSize: '0.7rem', fontWeight: 700, color: 'var(--color-text-secondary)', marginBottom: '0.5rem' }}>
                                    Card Title
                                </label>
                                <input
                                    type="text"
                                    required
                                    value={title}
                                    onChange={(e) => setTitle(e.target.value)}
                                    placeholder="e.g. Website redesign"
                                    style={{
                                        width: '100%',
                                        padding: '0.75rem',
                                        borderRadius: 'var(--radius-md)',
                                        border: '1px solid var(--color-border)',
                                        fontSize: '0.875rem',
                                        outline: 'none'
                                    }}
                                />
                            </div>

                            <div style={{ marginBottom: '1.5rem', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                                <div>
                                    <label style={{ display: 'block', textTransform: 'uppercase', fontSize: '0.7rem', fontWeight: 700, color: 'var(--color-text-secondary)', marginBottom: '0.5rem' }}>
                                        Priority
                                    </label>
                                    <select
                                        value={priority}
                                        onChange={(e) => setPriority(e.target.value)}
                                        style={{
                                            width: '100%',
                                            padding: '0.75rem',
                                            borderRadius: 'var(--radius-md)',
                                            border: '1px solid var(--color-border)',
                                            fontSize: '0.875rem',
                                            outline: 'none',
                                            backgroundColor: '#fff'
                                        }}
                                    >
                                        <option value="low">Low</option>
                                        <option value="medium">Medium</option>
                                        <option value="high">High</option>
                                    </select>
                                </div>
                                <div>
                                    <label style={{ display: 'block', textTransform: 'uppercase', fontSize: '0.7rem', fontWeight: 700, color: 'var(--color-text-secondary)', marginBottom: '0.5rem' }}>
                                        Assignee
                                    </label>
                                    <select
                                        value={assigneeId}
                                        onChange={(e) => setAssigneeId(e.target.value)}
                                        style={{
                                            width: '100%',
                                            padding: '0.75rem',
                                            borderRadius: 'var(--radius-md)',
                                            border: '1px solid var(--color-border)',
                                            fontSize: '0.875rem',
                                            outline: 'none',
                                            backgroundColor: '#fff'
                                        }}
                                    >
                                        <option value="">Select Assignee...</option>
                                        {users.map(u => (
                                            <option key={u.id} value={u.id}>{u.name}</option>
                                        ))}
                                    </select>
                                </div>
                            </div>

                            <div style={{ marginBottom: '1.5rem' }}>
                                <label style={{ display: 'block', textTransform: 'uppercase', fontSize: '0.7rem', fontWeight: 700, color: 'var(--color-text-secondary)', marginBottom: '0.5rem' }}>
                                    OPDSL (Due Date)
                                </label>
                                <input
                                    type="date"
                                    value={opdsl}
                                    onChange={(e) => setOpdsl(e.target.value)}
                                    style={{
                                        width: '100%',
                                        padding: '0.75rem',
                                        borderRadius: 'var(--radius-md)',
                                        border: '1px solid var(--color-border)',
                                        fontSize: '0.875rem',
                                        outline: 'none'
                                    }}
                                />
                            </div>
                        </>
                    ) : (
                        <>
                            <div style={{ marginBottom: '1.5rem' }}>
                                <label style={{ display: 'block', textTransform: 'uppercase', fontSize: '0.7rem', fontWeight: 700, color: 'var(--color-text-secondary)', marginBottom: '0.5rem' }}>
                                    Customer Name
                                </label>
                                <input
                                    type="text"
                                    required
                                    value={customerName}
                                    onChange={(e) => setCustomerName(e.target.value)}
                                    style={{
                                        width: '100%',
                                        padding: '0.75rem',
                                        borderRadius: 'var(--radius-md)',
                                        border: '1px solid var(--color-border)',
                                        fontSize: '0.875rem',
                                        outline: 'none'
                                    }}
                                />
                            </div>

                            <div style={{ marginBottom: '1.5rem' }}>
                                <label style={{ display: 'block', textTransform: 'uppercase', fontSize: '0.7rem', fontWeight: 700, color: 'var(--color-text-secondary)', marginBottom: '0.5rem' }}>
                                    Product Type
                                </label>
                                <input
                                    type="text"
                                    required
                                    value={productType}
                                    onChange={(e) => setProductType(e.target.value)}
                                    style={{
                                        width: '100%',
                                        padding: '0.75rem',
                                        borderRadius: 'var(--radius-md)',
                                        border: '1px solid var(--color-border)',
                                        fontSize: '0.875rem',
                                        outline: 'none'
                                    }}
                                />
                            </div>

                            <div style={{ marginBottom: '1.5rem' }}>
                                <label style={{ display: 'block', textTransform: 'uppercase', fontSize: '0.7rem', fontWeight: 700, color: 'var(--color-text-secondary)', marginBottom: '0.5rem' }}>
                                    Specs / Details
                                </label>
                                <textarea
                                    value={specs}
                                    onChange={(e) => setSpecs(e.target.value)}
                                    rows={4}
                                    style={{
                                        width: '100%',
                                        padding: '0.75rem',
                                        borderRadius: 'var(--radius-md)',
                                        border: '1px solid var(--color-border)',
                                        fontSize: '0.875rem',
                                        outline: 'none',
                                        fontFamily: 'inherit'
                                    }}
                                />
                            </div>

                            {/* Quote Cards also need a Title for the board view */}
                            <div style={{ marginBottom: '1.5rem' }}>
                                <label style={{ display: 'block', textTransform: 'uppercase', fontSize: '0.7rem', fontWeight: 700, color: 'var(--color-text-secondary)', marginBottom: '0.5rem' }}>
                                    Quote Title (Optional)
                                </label>
                                <input
                                    type="text"
                                    value={title}
                                    onChange={(e) => setTitle(e.target.value)}
                                    placeholder="e.g. Q1-2026 - Smith Corp"
                                    style={{
                                        width: '100%',
                                        padding: '0.75rem',
                                        borderRadius: 'var(--radius-md)',
                                        border: '1px solid var(--color-border)',
                                        fontSize: '0.875rem',
                                        outline: 'none'
                                    }}
                                />
                            </div>
                        </>
                    )}

                    <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', marginTop: '1rem' }}>
                        <button
                            type="button"
                            onClick={onClose}
                            className="btn"
                            style={{ background: 'transparent', border: '1px solid var(--color-border)', color: 'var(--color-text-secondary)' }}
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            className="btn btn-primary"
                        >
                            {editingCard ? 'Update' : (cardType === 'QUOTE' ? 'Create Quote' : 'Create Card')}
                        </button>
                    </div>
                </form>
            </div >
        </div >
    );
}
